
--
-- Auto-generated by AquaBot (2022-05-14 06:00)
-- https://www.aquabot.fr
--
AquaEventDb = {
  ["974786182053511218"] = {
    ["name"] = "Sepulcre hm suite",
    ["datetime"] = "2022-05-21 20:45",
    ["guild"] = {
      ["name"] = "Aqua Eterna",
      ["realm"] = "dalaran",
      ["region"] = "eu",
      ["locale"] = "fr_FR"
    },
    ["signups"] = {
      "kàlane-dalaran",
      "niunette-dalaran",
      "mzelledevill-dalaran",
      "idiina-dalaran"
    },
    ["leader"] = "niunette-dalaran"
  }
}