
--
-- Auto-generated by AquaBot (2022-04-19 00:00)
-- https://www.aquabot.fr
--
AquaEventDb = {
  ["965010087808729088"] = {
    ["name"] = "Event twitch",
    ["datetime"] = "2022-04-19 18:00",
    ["guild"] = {
      ["name"] = "Aqua Eterna",
      ["realm"] = "dalaran",
      ["region"] = "eu",
      ["locale"] = "fr_FR"
    },
    ["signups"] = {
      "mzelledevill-dalaran",
      "niunette-dalaran",
      "brumela-dalaran",
      "skeryn-dalaran"
    },
    ["leader"] = "mzelledevill-dalaran"
  }
}