
--
-- Auto-generated by AquaBot (2022-05-30 18:00)
-- https://www.aquabot.fr
--
AquaEventDb = {
  ["979859357892214896"] = {
    ["name"] = "Sepulcre hm suite",
    ["datetime"] = "2022-06-04 20:45",
    ["guild"] = {
      ["name"] = "Aqua Eterna",
      ["realm"] = "dalaran",
      ["region"] = "eu",
      ["locale"] = "fr_FR"
    },
    ["signups"] = {
      "æhlys-dalaran",
      "brumela-dalaran",
      "kàlane-dalaran",
      "mzelledevill-dalaran",
      "idiina-dalaran"
    },
    ["leader"] = "mzelledevill-dalaran"
  }
}